import { jsPDF } from 'jspdf'

const AGENTS = [
  { key: 'hallucination', label: 'Hallucination' },
  { key: 'safety', label: 'Safety' },
  { key: 'cost', label: 'Cost' },
  { key: 'compliance', label: 'Compliance' },
]

function verdictColor(verdict) {
  if (verdict === 'SAFE') return [16, 185, 129]
  if (verdict === 'CRITICAL') return [239, 68, 68]
  return [245, 158, 11]
}

/**
 * Generate and download a one-page Sentinel audit PDF.
 */
export function exportAuditPdf({
  sessionName,
  sessionId,
  verdict = 'UNKNOWN',
  overallScore = 0,
  agentScores = {},
  flags = [],
  generatedAt,
}) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const margin = 48
  let y = margin

  doc.setFillColor(17, 19, 24)
  doc.rect(0, 0, pageW, doc.internal.pageSize.getHeight(), 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.text('Sentinel Audit Report', margin, y)
  y += 28

  doc.setFontSize(11)
  doc.setTextColor(148, 163, 184)
  doc.text(sessionName || 'Unknown session', margin, y)
  y += 14
  doc.text(`Session ${(sessionId || '').slice(0, 12)}… · ${new Date(generatedAt || Date.now()).toLocaleString()}`, margin, y)
  y += 28

  const [r, g, b] = verdictColor(verdict)
  doc.setFillColor(r, g, b)
  doc.roundedRect(margin, y, 120, 28, 4, 4, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(12)
  doc.text(String(verdict), margin + 12, y + 18)

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(36)
  doc.text(String(Math.round(Number(overallScore) || 0)), margin + 140, y + 22)
  doc.setFontSize(12)
  doc.setTextColor(148, 163, 184)
  doc.text('/ 100', margin + 175, y + 22)
  y += 52

  doc.setTextColor(200, 210, 220)
  doc.setFontSize(13)
  doc.text('Agent Scores', margin, y)
  y += 16

  AGENTS.forEach((agent) => {
    const score = Math.round(Number(agentScores[agent.key] ?? 0))
    const barW = pageW - margin * 2 - 80
    doc.setTextColor(226, 232, 240)
    doc.setFontSize(11)
    doc.text(agent.label, margin, y + 10)
    doc.setTextColor(148, 163, 184)
    doc.text(String(score), pageW - margin - 20, y + 10, { align: 'right' })
    doc.setFillColor(40, 44, 52)
    doc.roundedRect(margin, y + 14, barW, 6, 2, 2, 'F')
    doc.setFillColor(99, 102, 241)
    doc.roundedRect(margin, y + 14, Math.max(4, (barW * score) / 100), 6, 2, 2, 'F')
    y += 32
  })

  y += 8
  doc.setTextColor(200, 210, 220)
  doc.setFontSize(13)
  doc.text(`Flags Raised (${flags.length})`, margin, y)
  y += 18

  if (flags.length === 0) {
    doc.setTextColor(148, 163, 184)
    doc.setFontSize(11)
    doc.text('No flags raised for this session.', margin, y)
    y += 20
  } else {
    flags.slice(0, 4).forEach((flag) => {
      if (y > 680) return
      doc.setTextColor(239, 68, 68)
      doc.setFontSize(10)
      doc.text(`${String(flag.severity || 'medium').toUpperCase()} · ${flag.flag_type || 'unknown'}`, margin, y)
      y += 12
      doc.setTextColor(226, 232, 240)
      doc.setFontSize(10)
      const desc = String(flag.description || '').slice(0, 120)
      const lines = doc.splitTextToSize(desc, pageW - margin * 2)
      doc.text(lines, margin, y)
      y += lines.length * 12 + 6
      const steps = flag.agent_verdict?.resolution_steps || []
      if (steps[0] && y < 700) {
        doc.setTextColor(148, 163, 184)
        doc.text(`Fix: ${String(steps[0]).slice(0, 90)}`, margin, y)
        y += 14
      }
      y += 6
    })
  }

  doc.setDrawColor(60, 65, 75)
  doc.line(margin, doc.internal.pageSize.getHeight() - 40, pageW - margin, doc.internal.pageSize.getHeight() - 40)
  doc.setTextColor(100, 116, 139)
  doc.setFontSize(9)
  doc.text('Generated by Sentinel · AI Agent Auditor', margin, doc.internal.pageSize.getHeight() - 24)

  const safeName = (sessionName || 'session').replace(/[^\w.-]+/g, '_').slice(0, 40)
  doc.save(`sentinel-audit-${safeName}.pdf`)
}
